#!name=Spotify
#!desc=unlock sp

[Rule]
DOMAIN,audio4-ak-spotify-com.akamaized.net
DOMAIN,cdn-spotify-experiments.conductrics.com
DOMAIN,heads-ak-spotify-com.akamaized.net
DOMAIN,spotify.com.edgesuite.net
DOMAIN,spotify.map.fastly.net
DOMAIN,spotify.map.fastlylb.net
DOMAIN-SUFFIX,audio-ak-spotify-com.akamaized.net
DOMAIN-SUFFIX,byspotify.com
DOMAIN-SUFFIX,heads4-ak-spotify-com.akamaized.net
DOMAIN-SUFFIX,pscdn.co
DOMAIN-SUFFIX,scdn.co
DOMAIN-SUFFIX,spoti.fi
DOMAIN-SUFFIX,spotify-com.akamaized.net
DOMAIN-SUFFIX,spotify-everywhere.com
DOMAIN-SUFFIX,spotify.com
DOMAIN-SUFFIX,spotify.design
DOMAIN-SUFFIX,spotifycdn.com
DOMAIN-SUFFIX,spotifycdn.net
DOMAIN-SUFFIX,spotifycharts.com
DOMAIN-SUFFIX,spotifycodes.com
DOMAIN-SUFFIX,spotifyforbrands.com
DOMAIN-SUFFIX,spotifyjobs.com
DOMAIN-SUFFIX,spotifynewsroom.jp
DOMAIN-SUFFIX,spotilocal.com
DOMAIN-SUFFIX,tospotify.com
DOMAIN-KEYWORD,-spotify-
DOMAIN-KEYWORD,spotify.com
USER-AGENT,Spotify*
IP-CIDR,104.154.127.126/32,no-resolve
IP-CIDR,35.186.224.47/32,no-resolve

[MITM]
hostname = %APPEND% spclient.wg.spotify.com

[Script]
spotify-json = type=http-request,type=http-request,pattern=^https:\/\/spclient\.wg\.spotify\.com\/(artistview\/v1\/artist|album-entity-view\/v2\/album)\/,requires-body=0,script-path=https://raw.githubusercontent.com/ahtungko/js/main/spjson.js
spotify-proto = type=http-response,pattern=^https:\/\/spclient\.wg\.spotify\.com\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)$,requires-body=1,binary-mode=1,max-size=0,script-path=https://raw.githubusercontent.com/ahtungko/js/main/spproto.js,script-update-interval=0
