name: Daily Commit

on:
  schedule:
    - cron: '0 12 * * *'  # Runs at 12:00 PM UTC (8:00 PM UTC+8)
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Set up Git user
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions[bot]"

      - name: Update yt.module with current UTC+8 date and time
        run: |
          currentTime=$(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S%z') # Get UTC+8 time
          sed -i "s/^#!Last Update:.*/#!Last Update: $currentTime/" yt.module || { echo "sed command failed" >&2; exit 1; }

      - name: Add changes
        run: git add . || { echo "git add failed" >&2; exit 1; }

      - name: Commit changes
        run: |
          if ! git diff-index --quiet HEAD --; then
            git commit -m "Daily update: $(TZ='Asia/Shanghai' date)" || { echo "git commit failed" >&2; exit 1; } # Commit message with UTC+8 time
          else
            echo "No changes to commit." >&2
          fi

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN_WRITE }}
          branch: main
        if: success()
